CREATE TABLE `report_detail_ui` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `report_id` bigint unsigned DEFAULT NULL COMMENT '所属报告ID',
  `execute_state` tinyint unsigned DEFAULT '0' COMMENT '执行状态',
  `assertion_state` tinyint unsigned DEFAULT '0' COMMENT '断言状态',
  `exception_msg` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci COMMENT '异常信息',
  `expand_time` bigint unsigned DEFAULT NULL COMMENT '消耗时间',
  `case_id` bigint unsigned DEFAULT NULL COMMENT '所属UI用例ID',
  `num` bigint unsigned DEFAULT NULL COMMENT '序号',
  `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '步骤名称',
  `operation_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '步骤操作类型',
  `location_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'UI元素定位类型',
  `location_express` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT 'UI元素定位表达式',
  `element_wait` bigint unsigned DEFAULT NULL COMMENT '元素查找最长等待时间',
  `target_location_type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '目标UI元素定位类型',
  `target_location_express` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '目标UI元素定位表达式',
  `target_element_wait` bigint unsigned DEFAULT NULL COMMENT '目标元素查找最长等待时间',
  `value` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '步骤值',
  `expect_key` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '预期属性',
  `expect_value` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '预期值',
  `description` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '步骤描述',
  `is_continue` tinyint unsigned DEFAULT NULL COMMENT '断言失败是否继续执行',
  `is_screenshot` tinyint unsigned DEFAULT NULL COMMENT '是否截图',
  `screenshot_url` varchar(1024) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '截图url',
  `gmt_create` datetime DEFAULT CURRENT_TIMESTAMP,
  `gmt_modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=158 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;