/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ApiCaseStep: typeof import('./../components/NewOrEdit/ApiCaseStep.vue')['default']
    EditableTable: typeof import('./../components/Table/EditableTable.vue')['default']
    ExecuteModal: typeof import('./../components/Execute/ExecuteModal.vue')['default']
    ExecuteResult: typeof import('./../components/Execute/ExecuteResult.vue')['default']
    ExecuteState: typeof import('./../components/Execute/ExecuteState.vue')['default']
    FormItemEnvironment: typeof import('./../components/FormItem/FormItemEnvironment.vue')['default']
    FormItemLevel: typeof import('./../components/FormItem/FormItemLevel.vue')['default']
    FormItemMethod: typeof import('./../components/FormItem/FormItemMethod.vue')['default']
    FormItemModules: typeof import('./../components/FormItem/FormItemModules.vue')['default']
    LayoutHeaderConfig: typeof import('./../components/Layouts/LayoutHeaderConfig.vue')['default']
    ModuleButton: typeof import('./../components/Module/ModuleButton.vue')['default']
    ModuleManager: typeof import('./../components/Module/ModuleManager.vue')['default']
    NewOrEditBody: typeof import('./../components/NewOrEdit/NewOrEditBody.vue')['default']
    NewOrEditFooter: typeof import('./../components/NewOrEdit/NewOrEditFooter.vue')['default']
    NewOrEditSteps: typeof import('./../components/NewOrEdit/NewOrEditSteps.vue')['default']
    PairTable: typeof import('./../components/Table/PairTable.vue')['default']
    ReportDetailsModalTable: typeof import('./../components/Report/ReportDetailsModalTable.vue')['default']
    ReportModalTable: typeof import('./../components/Report/ReportModalTable.vue')['default']
    RequestBody: typeof import('./../components/NewOrEdit/RequestBody.vue')['default']
    RequestConfig: typeof import('./../components/NewOrEdit/RequestConfig.vue')['default']
    ResizeableContainer: typeof import('./../components/Index/ResizeableContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimplyTableModal: typeof import('./../components/SimplyTableModal.vue')['default']
    TableModal: typeof import('./../components/TableModal.vue')['default']
    UploadFile: typeof import('./../components/UploadFile.vue')['default']
  }
}
